org: mayowafullstack
app: star-war
service: star-war
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  graphql:
    handler: src/index.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: 'tsconfig.json'

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-offline
